### ISSUE TITLE
Possible typo in OpenAPI specification

### ISSUE THREAD

**Issue by tymarats** [BroadbandForum/usp#24]
Is this a typo, should it be `updateServiceElementInstance` (singular) instead:

https://github.com/BroadbandForum/usp/blob/417b147abe1cc3610cf4d93e094f56d35cd72518/api/swagger-usp-controller-v1.yaml#L268

The semantics of the summary and the description for the operation strongly suggest that it is, as they're in line with those for GET and DELETE:

```
get:
      summary: Get Service Element instance by Name from USP Agent
      description: Retrieve an instance of the specified Service Element from a specific USP Agent
      operationId: getAgentServiceElement 

delete:
      summary: Delete Service Element instance by Name from USP Agent
      description: Update the USP Agent's configuration by removing an existing instance of the specified Service Element
      operationId: deleteAgentServiceElement

patch:
       summary: Update Service Element instance by Name on a USP Agent
       description: Update the USP Agent's configuration with the given instance of the specified Service Element
       operationId: updateAgentServiceElements
```
